services:
  aistudio-websocket-app:
    image: aistudio-websocket
    build: .
    pull_policy: never
    container_name: aistudio-websocket-app
    env_file:
      - .env
    volumes:
      - ./cookies:/app/cookies:rw
      - ./logs:/app/logs:rw
    restart: unless-stopped
